FROM node:18-alpine

WORKDIR /app

ARG PORT
ARG MONGO_URI
ARG APP_VERSION
ARG TOKEN_SECRET
ARG TWILIO_ACCOUNT_SID
ARG TWILIO_AUTH_TOKEN

ENV PORT=${PORT}
ENV MONGO_URI=${MONGO_URI}
ENV APP_VERSION=${APP_VERSION}
ENV TOKEN_SECRET=${TOKEN_SECRET}
ENV TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
ENV TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}


COPY . .

RUN npm install

RUN npm run build

EXPOSE $PORT

CMD [ "npm", "start" ]