version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: jhossuan/whynot-league:latest
    ports:
      - 5000:5000
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
    restart: always