name: Despliegue de API

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código fuente
        uses: actions/checkout@v2

      - name: Iniciar sesión en DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Construir y empujar imagen de Docker
        run: |
          docker-compose build
          docker-compose push
        
      - name: Configurar ambiente AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Conectarse a la instancia EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_IP_TEST }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo docker stop api-whynot
            sudo docker rm api-whynot
            sudo docker rmi jhossuan/whynot-league

            sudo docker build \
              --build-arg PORT=${{ secrets.PORT }} \
              --build-arg MONGO_URI=${{ secrets.MONGO_URI }} \
              --build-arg APP_VERSION=${{ secrets.APP_VERSION }} \
              --build-arg TOKEN_SECRET=${{ secrets.TOKEN_SECRET }} \
              --build-arg TWILIO_ACCOUNT_SID=${{ secrets.TWILIO_ACCOUNT_SID }} \
              --build-arg TWILIO_AUTH_TOKEN=${{ secrets.TWILIO_AUTH_TOKEN }} \
              -t jhossuan/whynot-league .

            sudo docker push jhossuan/whynot-league

            sudo docker run -d -p 5000:5000 --name api-whynot jhossuan/whynot-league
